# Change these first
owner: EsmailELBoBDev2 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - EsmailELBoBDev2

sites:
  - name: Main site - https://esmailelbob.xyz
    url: https://esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Libreddit - https://libreddit.esmailelbob.xyz
    url: https://libreddit.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Invidious - https://invidious.esmailelbob.xyz
    url: https://invidious.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Searx - https://searx.esmailelbob.xyz
    url: https://searx.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Nitter - https://nitter.esmailelbob.xyz
    url: https://nitter.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: rimgo - https://rimgo.esmailelbob.xyz
    url: https://rimgo.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Scribe - https://scribe.esmailelbob.xyz/
    url: https://scribe.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: WriteFreely - https://blog.esmailelbob.xyz
    url: https://blog.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Gitea - https://git.esmailelbob.xyz
    url: https://git.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Librarian - https://librarian.esmailelbob.xyz
    url: https://librarian.esmailelbob.xyz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Reddit Top RSS - https://rss-reddit.esmailelbob.xyz/
    url: https://rss-reddit.esmailelbob.xyz/?subreddit=memes
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: ProxiTok - https://proxitok.esmailelbob.xyz/
    url: https://proxitok.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: SimplyTranslate - https://simplytranslate.esmailelbob.xyz/
    url: https://simplytranslate.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: SimpleerTube - https://simpleertube.esmailelbob.xyz/
    url: https://simpleertube.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: PornInvidious - https://porninvidious.esmailelbob.xyz/
    url: https://porninvidious.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Minecraft Server - mc.esmailelbob.xyz
    check: "tcp-ping"
    url: mc.esmailelbob.xyz
    port: 25565
    maxResponseTime: 10000
#    expectedStatusCodes:
#      - 200
  - name: Pixelfed
    url: $PIXELFED
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Nextcloud
    url: $NEXTCLOUD
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Snikket
    url: $SNIKKET
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Mastodon - https://social.esmailelbob.xyz/
    url: https://social.esmailelbob.xyz/@esmail
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: MailCow
    url: $MAILCOW
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Pi-Hole
    url: $PIHOLE
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.esmailelbob.xyz
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "**Status Page**"
  introMessage: |
    If you have connection issues related to a website hosted by me, Check here to know if the problem on my end or yours
  navbar:
    - title: Status
      href: /
    - title: Source code
      href: https://git.esmailelbob.xyz/esmail/upptime
    - title: Donate
      href: https://donate.esmailelbob.xyz/
notifications:
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: esmail@esmailelbob.xyz
    NOTIFICATION_EMAIL_TO: esmail@esmailelbob.xyz
    NOTIFICATION_EMAIL_SMTP_PORT: 587
    NOTIFICATION_EMAIL_SMTP_HOST: mail.esmailelbob.xyz
    NOTIFICATION_EMAIL_SMTP_USERNAME: ${{ secrets.NOTIFICATION_EMAIL_USERNAME }}
    NOTIFICATION_EMAIL_SMTP_PASSWORD: ${{ secrets.NOTIFICATION_EMAIL_PASSWORD }}

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
