# Change these first
owner: EsmailELBoBDev2 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - EsmailELBoBDev2

sites:
  - name: Main site
    url: https://esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Bibliogram
    url: https://bibliogram.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Libreddit
    url: https://libreddit.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Invidious
    url: https://invidious.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: RSS-Bridge
    url: https://rss-bridge.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Searx
    url: https://searx.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Nitter
    url: https://nitter.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: WriteFreely
    url: $WRITEFREELY
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Pixelfed
    url: $PIXELFED
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Nextcloud
    url: $NEXTCLOUD
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Snikket
    url: $SNIKKET
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Mastodon
    url: $MASTODON
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: MailCow
    url: $MAILCOW
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Pi-Hole
    url: $PIHOLE
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.esmailelbob.xyz
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "**Status Page**"
  introMessage: If you have a hard time trying to connect to a website (*hosted by me ofc!*) check it here to know if it's a problem in my end or your end — Feel free to report any bugs/weird behaviors
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
notifications:
  NOTIFICATION_EMAIL_SMTP: true
  NOTIFICATION_EMAIL_SMTP_PORT: 587
  NOTIFICATION_EMAIL_SMTP_HOST: smtp.mailgun.org
  NOTIFICATION_EMAIL_SMTP_USERNAME: $SMTPUSERNAME
  NOTIFICATION_EMAIL_SMTP_PASSWORD: $SMTPPASSWORD
  NOTIFICATION_EMAIL: true
  NOTIFICATION_EMAIL_FROM: $FROMEMAIL
  NOTIFICATION_EMAIL_TO: $TOEMAIL
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
