# Change these first
owner: EsmailELBoBDev2 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - EsmailELBoBDev2

sites:
  - name: Main site - esmailelbob.xyz
    url: https://esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Libreddit - libreddit.esmailelbob.xyz
    url: https://libreddit.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Invidious - invidious.esmailelbob.xyz
    url: https://invidious.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Searx - searx.esmailelbob.xyz
    url: https://searx.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Nitter - nitter.esmailelbob.xyz
    url: https://nitter.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: rimgo - rimgo.esmailelbob.xyz
    url: https://rimgo.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Scribe - scribe.esmailelbob.xyz/
    url: https://scribe.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: WriteFreely - blog.esmailelbob.xyz
    url: https://blog.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Gitea - git.esmailelbob.xyz
    url: https://git.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Librarian - librarian.esmailelbob.xyz
    url: https://librarian.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Reddit Top RSS - rss-reddit.esmailelbob.xyz
    url: https://rss-reddit.esmailelbob.xyz/?subreddit=memes
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: ProxiTok - proxitok.esmailelbob.xyz
    url: https://proxitok.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: SimplyTranslate - simplytranslate.esmailelbob.xyz
    url: https://simplytranslate.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: SimpleerTube - simpleertube.esmailelbob.xyz
    url: https://simpleertube.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: PornInvidious - porninvidious.esmailelbob.xyz
    url: https://porninvidious.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: WikiLess - wikiless.esmailelbob.xyz
    url: https://wikiless.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: BeatBump - beatbump.esmailelbob.xyz
    url: https://beatbump.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Simplynews - simplynews.esmailelbob.xyz
    url: http://simplynews.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Piped - piped.esmailelbob.xyz
    url: http://piped.esmailelbob.xyz/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Minecraft Server - mc.esmailelbob.xyz
    check: "tcp-ping"
    url: mc.esmailelbob.xyz
    port: 25565
    maxResponseTime: 10000
#    expectedStatusCodes:
#      - 200
  - name: Pixelfed
    url: $PIXELFED
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Nextcloud
    url: $NEXTCLOUD
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Snikket
    url: $SNIKKET
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Mastodon - https://social.esmailelbob.xyz/
    url: https://social.esmailelbob.xyz/@esmail
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: MailCow
    url: $MAILCOW
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Pi-Hole
    url: $PIHOLE
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Jellyfin - jellyfin.esmailelbob.xyz
    url: https://jellyfin.esmailelbob.xyz/web/index.html
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200


status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.esmailelbob.xyz
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "**Status Page**"
  introMessage: |
    ```
    ———————————No major outage?———————————
    ⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
    ⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
    ⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
    ⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
    ⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
    ⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    —————————————————————————————
    ```
  navbar:
    - title: Status
      href: /
    - title: Source code
      href: https://git.esmailelbob.xyz/esmail/upptime
    - title: Donate
      href: https://donate.esmailelbob.xyz/
i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org) — Check out [Privacy Policy & Terms of service](https://github.com/EsmailELBoBDev2/upptime/blob/master/pri-tos.md)
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
