# Change these first
owner: EsmailELBoBDev2 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - EsmailELBoBDev2

sites:
  - name: Main site
    url: https://esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Bibliogram
    url: https://bibliogram.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Libreddit
    url: https://libreddit.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Invidious
    url: https://invidious.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: RSS-Bridge
    url: https://rss-bridge.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Searx
    url: https://searx.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Nitter
    url: https://nitter.esmailelbob.xyz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: WriteFreely
    url: $WRITEFREELY
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Pixelfed
    url: $PIXELFED
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Nextcloud
    url: $NEXTCLOUD
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Snikket
    url: $SNIKKET
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Mastodon
    url: $MASTODON
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: MailCow
    url: $MAILCOW
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Pi-Hole
    url: $PIHOLE
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

status-website: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.esmailelbob.xyz
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
